import logo from "./image 45.png";

export const friends = [
  {
    id: 1,
    logo: logo,
    name: "Whiskas",
    time: "day and night",
    address: "Grigorenka Street, 25",
    mapUrl: "//goo.gl/maps/JaeXyaPjUctLAAjX6?coh=178573&entry=tt",
    email: "whiskas@gmail.com",
    phone: "0–800–500–155",
    },
  {
    id: 2,
    logo: logo,
    name: "Whiskas",
    time: "day and night",
    address: "Grigorenka Street, 25",
    mapUrl: "//goo.gl/maps/JaeXyaPjUctLAAjX6?coh=178573&entry=tt",
    email: "whiskas@gmail.com",
    phone: "0–800–500–155",
    },
  {
    id: 3,
    logo: logo,
    name: "Whiskas",
    time: "day and night",
    address: "Grigorenka Street, 25",
    mapUrl: "//goo.gl/maps/JaeXyaPjUctLAAjX6?coh=178573&entry=tt",
    email: "whiskas@gmail.com",
    phone: "0–800–500–155",
    },
  {
    id: 4,
    logo: logo,
    name: "Whiskas",
    time: "day and night",
    address: "Grigorenka Street, 25",
    mapUrl: "//goo.gl/maps/JaeXyaPjUctLAAjX6?coh=178573&entry=tt",
    email: "whiskas@gmail.com",
    phone: "0–800–500–155",
    },
  {
    id: 5,
    logo: logo,
    name: "Whiskas",
    time: "day and night",
    address: "Grigorenka Street, 25",
    mapUrl: "//goo.gl/maps/JaeXyaPjUctLAAjX6?coh=178573&entry=tt",
    email: "whiskas@gmail.com",
    phone: "0–800–500–155",
    },
  {
    id: 6,
    logo: logo,
    name: "Whiskas",
    time: "day and night",
    address: "Grigorenka Street, 25",
    mapUrl: "//goo.gl/maps/JaeXyaPjUctLAAjX6?coh=178573&entry=tt",
    email: "whiskas@gmail.com",
    phone: "0–800–500–155",
    },
  {
    id: 7,
    logo: logo,
    name: "Whiskas",
    time: "day and night",
    address: "Grigorenka Street, 25",
    mapUrl: "//goo.gl/maps/JaeXyaPjUctLAAjX6?coh=178573&entry=tt",
    email: "whiskas@gmail.com",
    phone: "0–800–500–155",
  },
  {
    id: 8,
    logo: logo,
    name: "Whiskas",
    time: "day and night",
    address: "Grigorenka Street, 25",
    mapUrl: "//goo.gl/maps/JaeXyaPjUctLAAjX6?coh=178573&entry=tt",
    email: "whiskas@gmail.com",
    phone: "0–800–500–155",
  },
  {
    id: 9,
    logo: logo,
    name: "Whiskas",
    time: "day and night",
    address: "Grigorenka Street, 25",
    mapUrl: "//goo.gl/maps/JaeXyaPjUctLAAjX6?coh=178573&entry=tt",
    email: "whiskas@gmail.com",
    phone: "0–800–500–155",
    },

]