import logo from "./image 45.png";

export const friends = [
  {
    logo: logo,
    name: "Whiskas",
    time: "day and night",
    address: "Grigorenka Street, 25",
    mapUrl: "//goo.gl/maps/JaeXyaPjUctLAAjX6?coh=178573&entry=tt",
    email: "whiskas@gmail.com",
    phone: "0–800–500–155",
    },
  {
    logo: logo,
    name: "Whiskas",
    time: "day and night",
    address: "Grigorenka Street, 25",
    mapUrl: "//goo.gl/maps/JaeXyaPjUctLAAjX6?coh=178573&entry=tt",
    email: "whiskas@gmail.com",
    phone: "0–800–500–155",
    },
  {
    logo: logo,
    name: "Whiskas",
    time: "day and night",
    address: "Grigorenka Street, 25",
    mapUrl: "//goo.gl/maps/JaeXyaPjUctLAAjX6?coh=178573&entry=tt",
    email: "whiskas@gmail.com",
    phone: "0–800–500–155",
    },
  {
    logo: logo,
    name: "Whiskas",
    time: "day and night",
    address: "Grigorenka Street, 25",
    mapUrl: "//goo.gl/maps/JaeXyaPjUctLAAjX6?coh=178573&entry=tt",
    email: "whiskas@gmail.com",
    phone: "0–800–500–155",
    },
  {
    logo: logo,
    name: "Whiskas",
    time: "day and night",
    address: "Grigorenka Street, 25",
    mapUrl: "//goo.gl/maps/JaeXyaPjUctLAAjX6?coh=178573&entry=tt",
    email: "whiskas@gmail.com",
    phone: "0–800–500–155",
    },
  {
    logo: logo,
    name: "Whiskas",
    time: "day and night",
    address: "Grigorenka Street, 25",
    mapUrl: "//goo.gl/maps/JaeXyaPjUctLAAjX6?coh=178573&entry=tt",
    email: "whiskas@gmail.com",
    phone: "0–800–500–155",
    },
  {
    logo: logo,
    name: "Whiskas",
    time: "day and night",
    address: "Grigorenka Street, 25",
    mapUrl: "//goo.gl/maps/JaeXyaPjUctLAAjX6?coh=178573&entry=tt",
    email: "whiskas@gmail.com",
    phone: "0–800–500–155",
  },
   {
    logo: logo,
    name: "Whiskas",
    time: "day and night",
    address: "Grigorenka Street, 25",
    mapUrl: "//goo.gl/maps/JaeXyaPjUctLAAjX6?coh=178573&entry=tt",
    email: "whiskas@gmail.com",
    phone: "0–800–500–155",
  },
    {
    logo: logo,
    name: "Whiskas",
    time: "day and night",
    address: "Grigorenka Street, 25",
    mapUrl: "//goo.gl/maps/JaeXyaPjUctLAAjX6?coh=178573&entry=tt",
    email: "whiskas@gmail.com",
    phone: "0–800–500–155",
    },

]